window.esdocSearchIndex = [
  [
    "aureooms-js-itertools/src/base/stopiteration.js~stopiteration",
    "function/index.html#static-function-StopIteration",
    "<span>StopIteration</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/StopIteration.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/_count.js~_count",
    "function/index.html#static-function-_count",
    "<span>_count</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/_count.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/_next.js~_next",
    "function/index.html#static-function-_next",
    "<span>_next</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/_next.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/_product.js~_product",
    "function/index.html#static-function-_product",
    "<span>_product</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/_product.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/_range.js~_range",
    "function/index.html#static-function-_range",
    "<span>_range</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/_range.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/_reduce.js~_reduce",
    "function/index.html#static-function-_reduce",
    "<span>_reduce</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/_reduce.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/_sum.js~_sum",
    "function/index.html#static-function-_sum",
    "<span>_sum</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/_sum.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/_zip2.js~_zip2",
    "function/index.html#static-function-_zip2",
    "<span>_zip2</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/_zip2.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/_zip.js~_zip",
    "function/index.html#static-function-_zip",
    "<span>_zip</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/_zip.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/_ziplongest.js~_ziplongest",
    "function/index.html#static-function-_ziplongest",
    "<span>_ziplongest</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/_ziplongest.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/all.js~all",
    "function/index.html#static-function-all",
    "<span>all</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/all.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/any.js~any",
    "function/index.html#static-function-any",
    "<span>any</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/any.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/by.js~by",
    "function/index.html#static-function-by",
    "<span>by</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/by.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/chain.js~chain",
    "function/index.html#static-function-chain",
    "<span>chain</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/chain.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/combinations.js~combinations",
    "function/index.html#static-function-combinations",
    "<span>combinations</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/combinations.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/combinationswithrepetition.js~combinationswithrepetition",
    "function/index.html#static-function-combinationswithrepetition",
    "<span>combinationswithrepetition</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/combinationswithrepetition.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/compress.js~compress",
    "function/index.html#static-function-compress",
    "<span>compress</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/compress.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/consume.js~consume",
    "function/index.html#static-function-consume",
    "<span>consume</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/consume.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/count.js~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/count.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/cycle.js~cycle",
    "function/index.html#static-function-cycle",
    "<span>cycle</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/cycle.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/drop.js~drop",
    "function/index.html#static-function-drop",
    "<span>drop</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/drop.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/dropwhile.js~dropwhile",
    "function/index.html#static-function-dropwhile",
    "<span>dropwhile</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/dropwhile.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/enumerate.js~enumerate",
    "function/index.html#static-function-enumerate",
    "<span>enumerate</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/enumerate.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/exhaust.js~exhaust",
    "function/index.html#static-function-exhaust",
    "<span>exhaust</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/exhaust.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/filter.js~filter",
    "function/index.html#static-function-filter",
    "<span>filter</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/filter.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/filterfalse.js~filterfalse",
    "function/index.html#static-function-filterfalse",
    "<span>filterfalse</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/filterfalse.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/filter.js~filtertrue",
    "variable/index.html#static-variable-filtertrue",
    "<span>filtertrue</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/filter.js</span>",
    "variable"
  ],
  [
    "aureooms-js-itertools/src/base/frame.js~frame",
    "function/index.html#static-function-frame",
    "<span>frame</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/frame.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/group.js~group",
    "function/index.html#static-function-group",
    "<span>group</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/group.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/group.js~groupby",
    "variable/index.html#static-variable-groupby",
    "<span>groupby</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/group.js</span>",
    "variable"
  ],
  [
    "aureooms-js-itertools/src/base/head.js~head",
    "variable/index.html#static-variable-head",
    "<span>head</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/head.js</span>",
    "variable"
  ],
  [
    "aureooms-js-itertools/src/base/iter.js~iter",
    "function/index.html#static-function-iter",
    "<span>iter</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/iter.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/len.js~len",
    "function/index.html#static-function-len",
    "<span>len</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/len.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/list.js~list",
    "function/index.html#static-function-list",
    "<span>list</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/list.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/map.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/map.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/max.js~max",
    "function/index.html#static-function-max",
    "<span>max</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/max.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/min.js~min",
    "function/index.html#static-function-min",
    "<span>min</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/min.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/ncycle.js~ncycle",
    "function/index.html#static-function-ncycle",
    "<span>ncycle</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/ncycle.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/next.js~next",
    "function/index.html#static-function-next",
    "<span>next</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/next.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/nrepeat.js~nrepeat",
    "function/index.html#static-function-nrepeat",
    "<span>nrepeat</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/nrepeat.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/permutations.js~permutations",
    "function/index.html#static-function-permutations",
    "<span>permutations</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/permutations.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/pick.js~pick",
    "function/index.html#static-function-pick",
    "<span>pick</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/pick.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/product.js~product",
    "function/index.html#static-function-product",
    "<span>product</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/product.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/range.js~range",
    "function/index.html#static-function-range",
    "<span>range</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/range.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/reduce.js~reduce",
    "function/index.html#static-function-reduce",
    "<span>reduce</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/reduce.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/repeat.js~repeat",
    "function/index.html#static-function-repeat",
    "<span>repeat</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/repeat.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/reversed.js~reversed",
    "function/index.html#static-function-reversed",
    "<span>reversed</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/reversed.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/roundrobin.js~roundrobin",
    "function/index.html#static-function-roundrobin",
    "<span>roundrobin</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/roundrobin.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/slice.js~slice",
    "function/index.html#static-function-slice",
    "<span>slice</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/slice.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/some.js~some",
    "function/index.html#static-function-some",
    "<span>some</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/some.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/sorted.js~sorted",
    "function/index.html#static-function-sorted",
    "<span>sorted</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/sorted.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/starmap.js~starmap",
    "function/index.html#static-function-starmap",
    "<span>starmap</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/starmap.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/reduce/sum.js~sum",
    "function/index.html#static-function-sum",
    "<span>sum</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/reduce/sum.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/tail.js~tail",
    "function/index.html#static-function-tail",
    "<span>tail</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/tail.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/take.js~take",
    "function/index.html#static-function-take",
    "<span>take</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/take.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/takewhile.js~takewhile",
    "function/index.html#static-function-takewhile",
    "<span>takewhile</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/takewhile.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/tee.js~tee",
    "function/index.html#static-function-tee",
    "<span>tee</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/tee.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/base/trunc.js~trunc",
    "function/index.html#static-function-trunc",
    "<span>trunc</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/base/trunc.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/zip.js~zip",
    "function/index.html#static-function-zip",
    "<span>zip</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/zip.js</span>",
    "function"
  ],
  [
    "aureooms-js-itertools/src/map/ziplongest.js~ziplongest",
    "function/index.html#static-function-ziplongest",
    "<span>ziplongest</span> <span class=\"search-result-import-path\">aureooms-js-itertools/src/map/ziplongest.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/base/stopiteration.js",
    "file/src/base/StopIteration.js.html",
    "src/base/StopIteration.js",
    "file"
  ],
  [
    "src/base/_count.js",
    "file/src/base/_count.js.html",
    "src/base/_count.js",
    "file"
  ],
  [
    "src/base/_next.js",
    "file/src/base/_next.js.html",
    "src/base/_next.js",
    "file"
  ],
  [
    "src/base/_range.js",
    "file/src/base/_range.js.html",
    "src/base/_range.js",
    "file"
  ],
  [
    "src/base/by.js",
    "file/src/base/by.js.html",
    "src/base/by.js",
    "file"
  ],
  [
    "src/base/consume.js",
    "file/src/base/consume.js.html",
    "src/base/consume.js",
    "file"
  ],
  [
    "src/base/count.js",
    "file/src/base/count.js.html",
    "src/base/count.js",
    "file"
  ],
  [
    "src/base/cycle.js",
    "file/src/base/cycle.js.html",
    "src/base/cycle.js",
    "file"
  ],
  [
    "src/base/drop.js",
    "file/src/base/drop.js.html",
    "src/base/drop.js",
    "file"
  ],
  [
    "src/base/exhaust.js",
    "file/src/base/exhaust.js.html",
    "src/base/exhaust.js",
    "file"
  ],
  [
    "src/base/frame.js",
    "file/src/base/frame.js.html",
    "src/base/frame.js",
    "file"
  ],
  [
    "src/base/head.js",
    "file/src/base/head.js.html",
    "src/base/head.js",
    "file"
  ],
  [
    "src/base/index.js",
    "file/src/base/index.js.html",
    "src/base/index.js",
    "file"
  ],
  [
    "src/base/iter.js",
    "file/src/base/iter.js.html",
    "src/base/iter.js",
    "file"
  ],
  [
    "src/base/len.js",
    "file/src/base/len.js.html",
    "src/base/len.js",
    "file"
  ],
  [
    "src/base/list.js",
    "file/src/base/list.js.html",
    "src/base/list.js",
    "file"
  ],
  [
    "src/base/ncycle.js",
    "file/src/base/ncycle.js.html",
    "src/base/ncycle.js",
    "file"
  ],
  [
    "src/base/next.js",
    "file/src/base/next.js.html",
    "src/base/next.js",
    "file"
  ],
  [
    "src/base/pick.js",
    "file/src/base/pick.js.html",
    "src/base/pick.js",
    "file"
  ],
  [
    "src/base/range.js",
    "file/src/base/range.js.html",
    "src/base/range.js",
    "file"
  ],
  [
    "src/base/tail.js",
    "file/src/base/tail.js.html",
    "src/base/tail.js",
    "file"
  ],
  [
    "src/base/take.js",
    "file/src/base/take.js.html",
    "src/base/take.js",
    "file"
  ],
  [
    "src/base/tee.js",
    "file/src/base/tee.js.html",
    "src/base/tee.js",
    "file"
  ],
  [
    "src/base/trunc.js",
    "file/src/base/trunc.js.html",
    "src/base/trunc.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/map/_product.js",
    "file/src/map/_product.js.html",
    "src/map/_product.js",
    "file"
  ],
  [
    "src/map/_zip.js",
    "file/src/map/_zip.js.html",
    "src/map/_zip.js",
    "file"
  ],
  [
    "src/map/_zip2.js",
    "file/src/map/_zip2.js.html",
    "src/map/_zip2.js",
    "file"
  ],
  [
    "src/map/_ziplongest.js",
    "file/src/map/_ziplongest.js.html",
    "src/map/_ziplongest.js",
    "file"
  ],
  [
    "src/map/chain.js",
    "file/src/map/chain.js.html",
    "src/map/chain.js",
    "file"
  ],
  [
    "src/map/combinations.js",
    "file/src/map/combinations.js.html",
    "src/map/combinations.js",
    "file"
  ],
  [
    "src/map/combinationswithrepetition.js",
    "file/src/map/combinationswithrepetition.js.html",
    "src/map/combinationswithrepetition.js",
    "file"
  ],
  [
    "src/map/compress.js",
    "file/src/map/compress.js.html",
    "src/map/compress.js",
    "file"
  ],
  [
    "src/map/dropwhile.js",
    "file/src/map/dropwhile.js.html",
    "src/map/dropwhile.js",
    "file"
  ],
  [
    "src/map/enumerate.js",
    "file/src/map/enumerate.js.html",
    "src/map/enumerate.js",
    "file"
  ],
  [
    "src/map/filter.js",
    "file/src/map/filter.js.html",
    "src/map/filter.js",
    "file"
  ],
  [
    "src/map/filterfalse.js",
    "file/src/map/filterfalse.js.html",
    "src/map/filterfalse.js",
    "file"
  ],
  [
    "src/map/group.js",
    "file/src/map/group.js.html",
    "src/map/group.js",
    "file"
  ],
  [
    "src/map/index.js",
    "file/src/map/index.js.html",
    "src/map/index.js",
    "file"
  ],
  [
    "src/map/map.js",
    "file/src/map/map.js.html",
    "src/map/map.js",
    "file"
  ],
  [
    "src/map/nrepeat.js",
    "file/src/map/nrepeat.js.html",
    "src/map/nrepeat.js",
    "file"
  ],
  [
    "src/map/permutations.js",
    "file/src/map/permutations.js.html",
    "src/map/permutations.js",
    "file"
  ],
  [
    "src/map/product.js",
    "file/src/map/product.js.html",
    "src/map/product.js",
    "file"
  ],
  [
    "src/map/repeat.js",
    "file/src/map/repeat.js.html",
    "src/map/repeat.js",
    "file"
  ],
  [
    "src/map/reversed.js",
    "file/src/map/reversed.js.html",
    "src/map/reversed.js",
    "file"
  ],
  [
    "src/map/roundrobin.js",
    "file/src/map/roundrobin.js.html",
    "src/map/roundrobin.js",
    "file"
  ],
  [
    "src/map/slice.js",
    "file/src/map/slice.js.html",
    "src/map/slice.js",
    "file"
  ],
  [
    "src/map/sorted.js",
    "file/src/map/sorted.js.html",
    "src/map/sorted.js",
    "file"
  ],
  [
    "src/map/starmap.js",
    "file/src/map/starmap.js.html",
    "src/map/starmap.js",
    "file"
  ],
  [
    "src/map/takewhile.js",
    "file/src/map/takewhile.js.html",
    "src/map/takewhile.js",
    "file"
  ],
  [
    "src/map/zip.js",
    "file/src/map/zip.js.html",
    "src/map/zip.js",
    "file"
  ],
  [
    "src/map/ziplongest.js",
    "file/src/map/ziplongest.js.html",
    "src/map/ziplongest.js",
    "file"
  ],
  [
    "src/reduce/_reduce.js",
    "file/src/reduce/_reduce.js.html",
    "src/reduce/_reduce.js",
    "file"
  ],
  [
    "src/reduce/_sum.js",
    "file/src/reduce/_sum.js.html",
    "src/reduce/_sum.js",
    "file"
  ],
  [
    "src/reduce/all.js",
    "file/src/reduce/all.js.html",
    "src/reduce/all.js",
    "file"
  ],
  [
    "src/reduce/any.js",
    "file/src/reduce/any.js.html",
    "src/reduce/any.js",
    "file"
  ],
  [
    "src/reduce/index.js",
    "file/src/reduce/index.js.html",
    "src/reduce/index.js",
    "file"
  ],
  [
    "src/reduce/max.js",
    "file/src/reduce/max.js.html",
    "src/reduce/max.js",
    "file"
  ],
  [
    "src/reduce/min.js",
    "file/src/reduce/min.js.html",
    "src/reduce/min.js",
    "file"
  ],
  [
    "src/reduce/reduce.js",
    "file/src/reduce/reduce.js.html",
    "src/reduce/reduce.js",
    "file"
  ],
  [
    "src/reduce/some.js",
    "file/src/reduce/some.js.html",
    "src/reduce/some.js",
    "file"
  ],
  [
    "src/reduce/sum.js",
    "file/src/reduce/sum.js.html",
    "src/reduce/sum.js",
    "file"
  ]
]